### ISSUE TITLE
dead link at http://minisat.se/

### ISSUE THREAD

**Issue by keithbriggs** [niklasso/minisat-webpage#2]
The link at the end of 
> Finally! A new release of MiniSat, downloads/minisat-2.2.0.tar.gz. For more info, see the release notes. 
still doesn't work.
![screenshot from 2017-03-22 20 35 28](https://cloud.githubusercontent.com/assets/5146641/24219568/2b0162ee-0f3f-11e7-9704-b6e1784aac4e.png)

**Comment by sterin** [comment]
Oh, I thought you meant the release itself. 

The file itself was lost a few years ago when moving servers. Fortunately, The Internet Archive has a copy at
http://web.archive.org/web/20130521140402/http://minisat.se/downloads/ReleaseNotes-2.2.0.txt

**Comment by sterin** [comment]
File added from the copy at The Internet Archive. Thanks for the bug report.
The link at http://minisat.se/downloads/ReleaseNotes-2.2.0.txt should work now.
